language: python

python:
  - "2.7"
  - "3.6"

install:
  - pip install https://github.com/ladybug-tools/uwg/archive/master.zip
  - pip install pytest pytest-cov

script:
  - python -m pytest --cov=dragonfly
